version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - auth-app-network

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    networks:
      - auth-app-network

volumes:
  redisdata:

networks:
  auth-app-network:
